archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: freebsd
        goarch: arm64
    ldflags:
      - -s -w -X version.Version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'
changelog:
  skip: true
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
publishers:
  - name: hc-releases
    checksum: true
    signature: true
    cmd: hc-releases upload-file -header="x-terraform-protocol-version={{ .Env.PROTOCOL_VERSION }}" -header="x-terraform-protocol-versions={{ .Env.PROTOCOL_VERSIONS }}" {{ abs .ArtifactPath }}
    env:
      - AWS_ACCESS_KEY_ID={{ .Env.AWS_ACCESS_KEY_ID }}
      - AWS_SECRET_ACCESS_KEY={{ .Env.AWS_SECRET_ACCESS_KEY }}
release:
  ids:
    - none
signs:
  - args: ["-u", "{{ .Env.GPG_USER_ID }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
    artifacts: checksum
snapshot:
  name_template: "{{ .Tag }}-next"